version: '2'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "50m"
    max-file: "7"

services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    logging: *default-logging

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]
    networks:
      - 'default'
    logging: *default-logging
    ports:
      - '80:80'
      
  reference-ui:
    restart: always
    image: openlmisgm/gambia-ui:1.0.0
    env_file: settings.env
    depends_on: [consul]
    logging: *default-logging

  requisition:
    restart: always
    image: openlmis/requisition:${OL_REQUISITION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  referencedata:
    restart: always
    image: openlmis/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  auth:
    restart: always
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'auth-tomcat-log:/var/log/auth-tomcat'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  notification:
    restart: always
    image: openlmis/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Dspring.datasource.hikari.maximum-pool-size=10 -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  fulfillment:
    restart: always
    image: openlmis/fulfillment:${OL_FULFILLMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dspring.datasource.hikari.maximum-pool-size=15 -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging


  cce:
    restart: always
    image: openlmis/cce:${OL_CCE_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging


  stockmanagement:
    restart: always
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  report:
    restart: always
    image: openlmis/report:${OL_REPORT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    logging: *default-logging

  diagnostics:
    restart: always
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dspring.datasource.hikari.maximum-pool-size=10 -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging

  db:
    restart: always
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    env_file: settings.env
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - olmis-db
    depends_on: [consul]

  log:
    restart: always
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul
    logging: *default-logging

  service-configuration:
    build:
      context: config
    volumes:
      - service-config:/config

  ftp:
    image: hauptmedia/proftpd
    ports:
      - "21:21"
      - "20:20"
    env_file: settings.env
    depends_on: [consul]

  redis:
    image: redis:3.2.12
    depends_on: [consul]

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  auth-tomcat-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
  pg-data:
    external: true

networks:
  default:
    external: false